# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.AutoField(db_column='imageID', primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('imagehostpagedisplayurl', models.CharField(blank=True, db_column='imageHostPageDisplayURL', max_length=45, null=True)),
                ('imagehumaneval', models.IntegerField(blank=True, db_column='imageHumanEval', null=True)),
                ('imageracyscore', models.FloatField(db_column='imageRacyScore')),
                ('imageadultscore', models.FloatField(db_column='imageAdultScore')),
                ('imagename', models.CharField(blank=True, db_column='imageName', max_length=45, null=True)),
                ('imagethumbnail', models.TextField(blank=True, db_column='imageThumbnail', null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagemarket',
            fields=[
                ('imagemarketid', models.AutoField(db_column='imageMarketID', primary_key=True, serialize=False)),
                ('imagemarket', models.CharField(blank=True, db_column='imageMarket', max_length=45, null=True)),
                ('imagemarketdescription', models.CharField(blank=True, db_column='imageMarketDescription', max_length=45, null=True)),
            ],
            options={
                'db_table': 'imagemarket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imsource',
            fields=[
                ('imsourceid', models.AutoField(db_column='imsourceID', primary_key=True, serialize=False)),
                ('imsource', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'imsource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('languageid', models.AutoField(db_column='languageID', primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('languagecode', models.CharField(blank=True, db_column='languageCode', max_length=45, null=True)),
                ('languageimage', models.TextField(blank=True, db_column='languageImage', null=True)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pinyin',
            fields=[
                ('pinyinid', models.AutoField(db_column='pinyinID', primary_key=True, serialize=False)),
                ('pinyin', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pinyin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sourceid', models.AutoField(db_column='sourceID', primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translationid', models.AutoField(db_column='translationID', primary_key=True, serialize=False)),
                ('translation', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translationsource',
            fields=[
                ('translationsourceid', models.AutoField(db_column='translationSourceID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'translationsource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('wordid', models.AutoField(db_column='wordID', primary_key=True, serialize=False)),
                ('wordchinese', models.CharField(blank=True, db_column='wordChinese', max_length=45, null=True, unique=True)),
                ('wordcount', models.IntegerField(blank=True, db_column='wordCount', null=True)),
                ('wordpos', models.CharField(blank=True, db_column='wordPOS', max_length=45, null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wordimage',
            fields=[
                ('wordimageid', models.AutoField(db_column='wordImageID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wordimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wordpinyin',
            fields=[
                ('wordpinyinid', models.AutoField(db_column='wordPinyinID', primary_key=True, serialize=False)),
                ('wordpinyinpreferred', models.IntegerField(blank=True, db_column='wordPinyinPreferred', null=True)),
            ],
            options={
                'db_table': 'wordpinyin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wordtranslation',
            fields=[
                ('wordtranslationid', models.AutoField(db_column='wordTranslationID', primary_key=True, serialize=False)),
                ('wordtranslationeval', models.IntegerField(blank=True, db_column='wordTranslationEval', null=True)),
            ],
            options={
                'db_table': 'wordtranslation',
                'managed': False,
            },
        ),
    ]
